//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gexpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIT_DOC_ESTADO
    {
        public int BIT_ID { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public string ARCHIVO_CORRELATIVO { get; set; }
        public string ESTADO_ANT { get; set; }
        public string ESTADO_ACT { get; set; }
        public Nullable<int> ARCHIVO_ID { get; set; }
    }
}
