//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gexpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCUMENTO()
        {
            this.BUZON = new HashSet<BUZON>();
            this.EXPEDIENTE = new HashSet<EXPEDIENTE>();
        }
    
        public int ARCHIVO_ID { get; set; }
        public string ARCHIVO_USUARIO { get; set; }
        public Nullable<int> DEPARTAMENTO { get; set; }
        public Nullable<int> INSTITUCION { get; set; }
        public Nullable<int> ARCHIVO_TIPO_ID { get; set; }
        public Nullable<System.DateTime> ARCHIVO_FECHA_DOCUMENTO { get; set; }
        public string ARCHIVO_CORRELATIVO { get; set; }
        public string ARCHIVO_ASUNTO { get; set; }
        public string ARCHIVO_ANEXO_RUTA { get; set; }
        public string ARCHIVO_OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> ARCHIVO_FECHA_CREA { get; set; }
        public int ESTADO_ID { get; set; }
        public int TIPO_ID { get; set; }
        public int DEPARTAMENTO_ID { get; set; }
        public int INSTITUCION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUZON> BUZON { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPEDIENTE> EXPEDIENTE { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual INSTITUCION INSTITUCION1 { get; set; }
        public virtual TIPO_ARCHIVO TIPO_ARCHIVO { get; set; }
    }
}
