//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gexpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPEDIENTE
    {
        public int EXPEDIENTE_ID { get; set; }
        public Nullable<System.DateTime> FECH_CREA { get; set; }
        public string USUARIO_CREA { get; set; }
        public int ARCHIVO_ID { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
