//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gexpedientes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionDeExpEntities : DbContext
    {
        public GestionDeExpEntities()
            : base("name=GestionDeExpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIT_DOC_ESTADO> BIT_DOC_ESTADO { get; set; }
        public virtual DbSet<BUZON> BUZON { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DOCUMENTO> DOCUMENTO { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<EXPEDIENTE> EXPEDIENTE { get; set; }
        public virtual DbSet<INSTITUCION> INSTITUCION { get; set; }
        public virtual DbSet<PERMISO> PERMISO { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<ROL_PERMISO> ROL_PERMISO { get; set; }
        public virtual DbSet<TIPO_ARCHIVO> TIPO_ARCHIVO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
