//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gexpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTITUCION()
        {
            this.DOCUMENTO = new HashSet<DOCUMENTO>();
        }
    
        public int INSTITUCION_ID { get; set; }
        public string INSTITUCION_NOMBRE { get; set; }
        public string INSTITUCION_ABREVIATURA { get; set; }
        public string INSTITUCION_DIRECCION { get; set; }
        public string INSTITUCION_TELEFONO { get; set; }
        public string INSTITUCION_WEB { get; set; }
        public string INSTITUCION_ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
    }
}
