//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gexpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_PERMISO
    {
        public int CORRELATIVO { get; set; }
        public int ROL_ID { get; set; }
        public int PERMISO_ID { get; set; }
    
        public virtual PERMISO PERMISO { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
