//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gexpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int USUARIO_ID { get; set; }
        public Nullable<System.DateTime> USUARIO_FECHA_CREA { get; set; }
        public string USUARIO_CODIGO { get; set; }
        public string USUARIO_NICK { get; set; }
        public string USUARIO_PASSWORD { get; set; }
        public Nullable<int> ROL_ID { get; set; }
        public string USUARIO_EMAIL { get; set; }
        public string USUARIO_NOMBRE1 { get; set; }
        public string USUARIO_NOMBRE2 { get; set; }
        public string USUARIO_APELLIDO1 { get; set; }
        public string USUARIO_APELLIDO2 { get; set; }
        public Nullable<int> USUARIO_DEPARTAMENTO { get; set; }
        public string TITULO { get; set; }
        public string USUARIO_PUESTO { get; set; }
        public Nullable<int> USUARIO_STATUS { get; set; }
        public int ESTADO_ID { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
